### ISSUE TITLE
This app can't be installed.

### ISSUE THREAD

**Issue by idanblich** [RatanPaul/Salesforce-Lightning-Dynamic-Datatable#1]
Got this when try to install :
This app can't be installed.
There are problems that prevent this package from being installed.
Cannot mark attributes 'query' as required without specifying default values when the component implements interface force:appHostable. : 

> Cannot mark attributes 'query' as required without specifying default values when the component implements interface force:appHostable.

**Comment by RatanPaul** [comment]
Issue fixed with Version 1.2.

Install this updated package

https://login.salesforce.com/packaging/installPackage.apexp?p0=04t90000000Y1an
