### ISSUE TITLE
Can't open the app when LockerService Security enabled

### ISSUE THREAD

**Issue by jega555** [RatanPaul/Salesforce-Lightning-Dynamic-Datatable#2]
When I try to open app it shows error popup

Uncaught TypeError: Option is not a constructor

throws at /resource/Dynamic_DataTable/js/datatables.min.js:66:448

This occurs only when LockerService security critical update enabled.

![image](https://cloud.githubusercontent.com/assets/20640728/17099539/96b2c292-5286-11e6-8f08-0517fdfd86c8.png)

**Comment by dollykansal** [comment]
Me too facing this issue.
I even disabled the LockerService security update.
Still, getting the error.

Also, I never get the Search,Pagination or Sorting options, is it due to error???
Though, I cant seem to find the code in the installed components as well. Am I missing something???

**Comment by RatanPaul** [comment]
you can set the global access that may solve this issue. 

```
<aura:component access="GLOBAL">

 </aura:component>
```

**Comment by jega555** [comment]
I already set global access to the component and the app. Unfortunately still I'm getting the same error message.

**Comment by RatanPaul** [comment]
is this issue occurred with newly developer org or you guys getting this issue in sandbox ? can you please provide me the details so I can easily replicate this issue?

**Comment by jega555** [comment]
I'm getting this issue in sandbox - unlimited edition

**Comment by Prasadsfdc** [comment]
Hi Ratan,

I have install the your unmanaged package in my personal org and also deactivated the locker service but still getting the  below issue.

Uncaught TypeError: Option is not a constructor
throws at /resource/Dynamic_DataTable/js/datatables.min.js:66:448

Regards,
Bishnu

**Comment by RatanPaul** [comment]
So this is an known bug in salesforce locker system.  This should be fixed in winter 17 release or after that. 

Check this theard http://salesforce.stackexchange.com/q/143371/18731

**Comment by RatanPaul** [comment]
Guys there is another component I have build check this out https://github.com/RatanPaul/salesforce-lightning-slds-table

**Comment by RatanPaul** [comment]
Looks like this issue is resolved now. I have tested in my org.
