### ISSUE TITLE
Uncaught TypeError: Option is not a constructor

### ISSUE THREAD

**Issue by Prasadsfdc** [RatanPaul/Salesforce-Lightning-Dynamic-Datatable#3]
Hi Ratan,

I have install the your unmanaged package in my personal org and also deactivated the locker service but still getting the below issue.

Uncaught TypeError: Option is not a constructor
throws at /resource/Dynamic_DataTable/js/datatables.min.js:66:448

Regards,
Bishnu

**Comment by RatanPaul** [comment]
continue discussion here https://github.com/RatanPaul/Salesforce-Lightning-Dynamic-Datatable/issues/2
