### ISSUE TITLE
Css problems 

### ISSUE THREAD

**Issue by danhowellnz** [RatanPaul/Salesforce-Lightning-Dynamic-Datatable#5]
The css file is impacting everything else on the page. For example, it is applyiny font-size:10px to everything in html. 

![image](https://user-images.githubusercontent.com/21028276/28648354-5744f47a-72c1-11e7-9cad-a494cc16eddd.png)

**Comment by RatanPaul** [comment]
This is because of bootstrap css. I would suggest dont use bootstrap css. instead of use only jquery ui css. 

check this example https://datatables.net/examples/basic_init/zero_configuration.html without bootstrap.
