### ISSUE TITLE
Some customisaton work

### ISSUE THREAD

**Issue by danhowellnz** [RatanPaul/Salesforce-Lightning-Dynamic-Datatable#6]
Hi, 

I was wondering if you could help me with a project. Look at using datatables and then having two editable fields that can be input into and changed and saved. 

I don't know if using  the editor https://editor.datatables.net/ is the best approach. 
I would be able to pay you to help out. Contact me at daniel@gravitylab.nz and we can see if it works for you.

**Comment by RatanPaul** [comment]
check this https://github.com/jphustman/jquery-datatables-editable
